name = "kakeibo"
main = "src/index.js"
compatibility_date = "2024-04-01"
account_id = "1c943e2b7083c714e0ac8f720b381113"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "kakeibo-db"
database_id = "76cdb8e6-15a7-473a-a87a-4132c98238e0"

[[r2_buckets]]
binding = "RECEIPT_BUCKET"
bucket_name = "kakeibo-receipts"
